name: Update flake inputs

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v7

      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update flake inputs
        run: nix flake update

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          commit-message: "chore: update flake inputs"
          title: "chore: update flake inputs"
          body: Automated flake inputs update by GitHub Actions.
          branch: update/flake-inputs
          labels: automated
          delete-branch: true
